name: .NET 10 Build & Test

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.slnx"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.slnx"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: '**/*.slnx'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release  --nologo

      - name: Run tests
        run: dotnet test -c Release --no-build -v normal --nologo
